kind: Pod
apiVersion: v1
metadata:
  name: health
  labels:
    app: health
spec:
  containers:
  - command:
    - /agnhost
    - netexec
    - --http-port
    - "8080"
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
    name: health
---
kind: Service
apiVersion: v1
metadata:
  name: svc-health
spec:
  selector:
    app: health
  ports:
  # Default port used by the image
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-health
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /health
        backend:
          service:
            name: svc-health
            port:
              number: 8080
---
